import Head from 'next/head'
import Nav from '../components/Nav'

export default function About() {
  return (
    <div>

      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <h1>This Is About Page</h1>
    </div>
  )
}
