
import Head from 'next/head'
import Nav from '../components/Nav'
import {SearchIcon , CloseIcon} from "@chakra-ui/icons"
  
 
  import Character from '../components/Characters';
import { useState } from 'react';
import { ApolloClient,InMemoryCache, gql } from '@apollo/client';
import { Heading , Box , Flex , Input , Stack , IconButton , useToast } from '@chakra-ui/react';
export default function Home(results) {
    const [search,setSearch] = useState('');
  const toast = useToast();
  const initialState = results;
  const [characters , setCharacters]=useState(initialState.characters);
  console.log(initialState)
  return (
    <Flex direction="column" justify="center" align="center">
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <form onSubmit={
          async (e) => {
            e.preventDefault();
            const res = await fetch("/api/SearchCharacter", {
              method: "post",
              body: search,
    
            });
            console.log(search);
            const {characters , error} = await res.json();
            if(error)
            {
              toast({
                position : "bottom",
                title:"An Error occured",
                description: error,
                duration:5000,
                isClosable : true,
              })
            }
            else{
              
              setCharacters(characters);
            }
          }
         }>
        <Stack maxWidth="300px" isInline mb={8}>
          <Input placeholder = "Search ..." border="none" value={search} onChange={(e)=>setSearch(e.target.value)}></Input>
          <IconButton colorScheme="green" arial-label="Search Database" icon={<SearchIcon/>} disabled={search===""} type="submit"></IconButton>
          <IconButton colorScheme="blue" arial-label="Reset Button" icon={<CloseIcon/>} disable={search ===""} onclick = {async () => {setSearch(""); setCharacters(initialState.characters)}} />
        </Stack>
      </form>
     <Box mb={4} flexDirectio n="column" align="center" justify="center" py={8}>
      <Heading as="h1" size="2x1" mb={8}>Rick and Morty</Heading>
      <Character characters={characters} ></Character>
     </Box>
    </Flex>
  )
}
export async function getStaticProps(){
  const client = new ApolloClient({
    uri: "https://rickandmortyapi.com/graphql/",
    cache : new InMemoryCache(),
  })
  const {data} = await client.query(
    {
      query: gql`
      query{
  characters(page: 1){
    info{
      count
      pages
    }
    results{
      name
      id
      location{
        id
      	name
      }
      origin{
        id
        name
      }
      episode{
        id
      	episode
      	air_date
      }
      image
    }
  }
}
      `,
    }
  );
  return{
    props:{
      characters : data.characters.results,
    }
  }

}
